# Generated by Django 2.1.7 on 2019-11-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0004_auto_20191119_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counter',
            name='valor',
        ),
        migrations.AddField(
            model_name='counter',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
