# Generated by Django 2.1.7 on 2019-11-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0006_auto_20191120_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='date',
            field=models.DateField(default='2019-11-22'),
        ),
    ]
