# Generated by Django 2.2.7 on 2019-11-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0007_auto_20191122_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='date',
            field=models.DateField(default='2019-11-23'),
        ),
    ]
