# Generated by Django 2.2.7 on 2019-11-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0009_auto_20191124_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='date',
            field=models.DateField(default='2019-11-25'),
        ),
    ]
