# Generated by Django 2.1.7 on 2019-11-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0010_auto_20191125_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='date',
            field=models.DateField(default='2019-11-26'),
        ),
    ]
