# Generated by Django 2.2.7 on 2019-12-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0014_auto_20191210_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='date',
            field=models.DateField(default='2019-12-12'),
        ),
    ]
