# Generated by Django 2.2.7 on 2019-12-12 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0015_auto_20191212_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.IntegerField(null=True),
        ),
    ]
