# Generated by Django 2.2.7 on 2019-12-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0016_game_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
