# Generated by Django 2.2.7 on 2020-06-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0018_auto_20200530_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='date',
            field=models.DateField(default='2020-06-04'),
        ),
    ]
